config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :sessions
  resources :registrations
  match "/signup", to: "registrations#new", via: :get, as: :signup
  match "/signup", to: "registrations#create", via: :post
  match "/login", to: "sessions#new", via: :get, as: :login
  match "/logout", to: "sessions#destroy", via: :delete, as: :logout
  root "sessions#new"
  resources :events, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :first_name, :email, presence: true
	validates :role, inclusion: { in: %w(user admin), message: "%{value} is not a valid role" }
	validates :email, uniqueness: true
	after_create :create_user_in_iterable

	def full_name
		"#{first_name} #{last_name}"
	end

	def is_admin?
		role == "admin"
	end

	private
		def create_user_in_iterable
			begin
				Iterable::User.create(self)
			rescue => e
				Rails.logger.info(e.message);
			end
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    def current_user
        @current_user ||= User.find(session[:user_id]) unless session[:user_id].nil?
    end
    helper_method :current_user

    def authendicate_user!
        redirect_to new_session_path, alert: "You must login to access!" unless current_user
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
		before_action :authendicate_user!

		# create event in Iterable
		def create
			begin
				event = Iterable::Event.create(current_user.email,params[:name])
				if event&.code == "Success"
					redirect_to events_path, notice: "Event created successfully"
				else
					redirect_to events_path, alert: "Unable to create event. #{event&.msg}"
				end
			rescue => e
				redirect_to events_path, alert: "Unable to create event. #{e.message}"
			end
		end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
      @user = User.new
    end
    
    def create
      @user = User.new(user_params)
			if @user.save
				session[:user_id] = @user.id
				redirect_to events_path, notice: "Registered successfully!"
			else
				puts @user.errors.any?
        flash.now[:error] = "Unable to register!"
        render :new
      end
    end
    
    private
        def user_params
            params.require(:user).permit(:first_name, :last_name, :email, :phone, :password, :password_confirmation)
        end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
      # Render the login form
      @user = User.new
    end
    
    def create
      # Find the user by email
      user = User.find_by(email: params[:email])
      
      # If the user exists and the password is correct
      if user && user.authenticate(params[:password])
        # Save the user's ID in the session and redirect to the events page
        session[:user_id] = user.id
        redirect_to events_path
      else
        # Show an error message and render the login form again
        flash.now[:error] = "Invalid email or password"
        render :new
      end
    end
    
    def destroy
      # Clear the session and redirect to the login page
      session[:user_id] = nil
      redirect_to login_path, notice: "Logout successfully!"
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/common/_alert.html.erb
<% if notice %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>
<% if alert %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Iterable</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
			<% if current_user %>
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="<%=events_path %>">Events</a>
					</li>
          <li class="nav-item">
						<%= link_to "Signout", logout_path, class: "nav-link", data: {turbo_method: :delete} %>
					</li>
				</ul>
			<% end %>
    </div>
  </div>
</nav>

app/views/events/index.html.erb
<div class="container">
    <h1>Events</h1>
    <br/><br/>
    <%= form_with url: events_path(name: 'Event A'), data: { turbo: false } do |f| %>
        <%= f.submit 'Create Event A', class: 'btn btn-primary' %>
    <% end %>
    <br/><br/><br/>
    <%= form_with url: events_path(name: 'Event B'), data: { turbo: false } do |f| %>
        <%= f.submit 'Create Event B', class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Iterable Notifier</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "common/navbar" %>
    <div class="container">
      <%= render "common/alert" %>
      <%= yield %>
    </div>
  </body>
</html>